project_id = "hdjgkjceownmmnrqqtuz"

[functions.analyze-task-priority]
verify_jwt = false

[functions.users-admin-actions]
verify_jwt = false

[functions.roles-admin]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.auth-actions]
verify_jwt = false

[functions.mns-response-generator]
verify_jwt = false

[functions.bepaid-create-token]
verify_jwt = false

[functions.bepaid-webhook]
verify_jwt = false

[functions.merge-clients]
verify_jwt = false

[functions.detect-duplicates]
verify_jwt = false

[functions.amocrm-sync]
verify_jwt = false

[functions.amocrm-webhook]
verify_jwt = false

[functions.integration-healthcheck]
verify_jwt = false

[functions.getcourse-webhook]
verify_jwt = false
