project_id = "hdjgkjceownmmnrqqtuz"

[functions.analyze-task-priority]
verify_jwt = true

[functions.users-admin-actions]
verify_jwt = false

[functions.roles-admin]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.auth-actions]
verify_jwt = false

[functions.mns-response-generator]
verify_jwt = true

[functions.bepaid-create-token]
verify_jwt = false

[functions.bepaid-webhook]
verify_jwt = false

[functions.merge-clients]
verify_jwt = true

[functions.detect-duplicates]
verify_jwt = true

[functions.amocrm-sync]
verify_jwt = true

[functions.amocrm-webhook]
verify_jwt = false

[functions.integration-healthcheck]
verify_jwt = true

[functions.getcourse-webhook]
verify_jwt = false

[functions.integration-sync]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-grant-access]
verify_jwt = false

[functions.telegram-revoke-access]
verify_jwt = false

[functions.telegram-check-expired]
verify_jwt = false

[functions.telegram-bot-actions]
verify_jwt = false

[functions.telegram-send-reminders]
verify_jwt = false

[functions.telegram-send-notification]
verify_jwt = false

[functions.telegram-mass-broadcast]
verify_jwt = false

[functions.telegram-club-members]
verify_jwt = false

[functions.telegram-mtproto-sync]
verify_jwt = true

[functions.telegram-cron-sync]
verify_jwt = false

[functions.telegram-kick-violators]
verify_jwt = false

[functions.getcourse-sync]
verify_jwt = true

[functions.subscription-charge]
verify_jwt = false

[functions.public-product]
verify_jwt = false

[functions.cancel-trial]
verify_jwt = true

[functions.telegram-link-manage]
verify_jwt = false
